SELECT f.FLAVOR
FROM FIRST_HALF f
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
        FROM JULY
        GROUP BY
            FLAVOR
    ) j ON f.flavor = j.flavor
ORDER BY f.TOTAL_ORDER + j.JULY_ORDER DESC
LIMIT 3